/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsAndConditionsImport } from './routes/terms-and-conditions'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as PracticeImport } from './routes/practice'
import { Route as AboutUsImport } from './routes/about-us'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TermsAndConditionsRoute = TermsAndConditionsImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const PracticeRoute = PracticeImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/practice': typeof PracticeRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/practice'
    | '/privacy'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about-us' | '/practice' | '/privacy' | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/practice'
    | '/privacy'
    | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  PracticeRoute: typeof PracticeRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  PracticeRoute: PracticeRoute,
  PrivacyRoute: PrivacyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about-us",
        "/practice",
        "/privacy",
        "/terms-and-conditions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about-us": {
      "filePath": "about-us.tsx"
    },
    "/practice": {
      "filePath": "practice.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/terms-and-conditions": {
      "filePath": "terms-and-conditions.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
